/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Openapicmv1clientrenewalsRenewalEntityIdRenewalData struct {
	AustraliaData *interface{} `json:"AustraliaData,omitempty"`
	PersonalInformation *interface{} `json:"PersonalInformation,omitempty"`
	ProfileInformation *interface{} `json:"ProfileInformation,omitempty"`
	RegulatoryInformation *interface{} `json:"RegulatoryInformation,omitempty"`
	SingaporeData *interface{} `json:"SingaporeData,omitempty"`
}
