/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body struct {
	DisplayName            string  `json:"DisplayName,omitempty"`
	FundingAccountKey      string  `json:"FundingAccountKey,omitempty"`
	InitialFunding         float64 `json:"InitialFunding,omitempty"`
	InvestmentShieldAmount float64 `json:"InvestmentShieldAmount,omitempty"`
	IsDisclaimerAccepted   bool    `json:"IsDisclaimerAccepted,omitempty"`
	TradeLeaderId          string  `json:"TradeLeaderId,omitempty"`
}
