/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body73 struct {
	AccountKey string `json:"AccountKey,omitempty"`
	Amount float64 `json:"Amount,omitempty"`
	AmountType []string `json:"AmountType,omitempty"`
	AssetType []string `json:"AssetType,omitempty"`
	BuySell []string `json:"BuySell,omitempty"`
	DecisionMakerUserID int32 `json:"DecisionMakerUserID,omitempty"`
	ExternalReference string `json:"ExternalReference,omitempty"`
	FieldGroups []interface{} `json:"FieldGroups,omitempty"`
	ForwardDate string `json:"ForwardDate,omitempty"`
	IsForceOpen bool `json:"IsForceOpen,omitempty"`
	OrderDuration *interface{} `json:"OrderDuration,omitempty"`
	OrderPrice float64 `json:"OrderPrice,omitempty"`
	OrderType []string `json:"OrderType,omitempty"`
	PositionId string `json:"PositionId,omitempty"`
	StopLimitPrice float64 `json:"StopLimitPrice,omitempty"`
	StrategyId string `json:"StrategyId,omitempty"`
	SwitchInstrumentUic int32 `json:"SwitchInstrumentUic,omitempty"`
	ToOpenClose []string `json:"ToOpenClose,omitempty"`
	TraspasoIn *interface{} `json:"TraspasoIn,omitempty"`
	Uic int32 `json:"Uic,omitempty"`
}
