/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body21 struct {
	Attachment *Openapicsv1partnersupportcasesCaseIdnoteAttachment `json:"Attachment,omitempty"`
	Note       string                                              `json:"Note,omitempty"`
	Title      string                                              `json:"Title,omitempty"`
}
