/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Openapicsv2cashmanagementwithdrawalsWithdrawIBanSwiftAdvancedOptions struct {
	IntermediaryBank string `json:"IntermediaryBank,omitempty"`
	RegulatedBroker *interface{} `json:"RegulatedBroker,omitempty"`
	RequestClosureOfAccount string `json:"RequestClosureOfAccount,omitempty"`
}
