/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type InlineResponse400 struct {
	ErrorCode string `json:"ErrorCode,omitempty"`
	Message string `json:"Message,omitempty"`
	ModelState *interface{} `json:"ModelState,omitempty"`
}
