/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body2 struct {
	Amount float64 `json:"Amount,omitempty"`
	TargetAccountKey string `json:"TargetAccountKey,omitempty"`
}
