/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body5 struct {
	OverallSuitability []string `json:"OverallSuitability,omitempty"`
	ProductAreaSuitability []string `json:"ProductAreaSuitability,omitempty"`
}
