/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body55 struct {
	ContextId   string `json:"ContextId,omitempty"`
	Format      string `json:"Format,omitempty"`
	ReferenceId string `json:"ReferenceId,omitempty"`
	RefreshRate int32  `json:"RefreshRate,omitempty"`
	Tag         string `json:"Tag,omitempty"`
}
