/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body61 struct {
	AppHint int32 `json:"AppHint,omitempty"`
	BuySell []string `json:"BuySell,omitempty"`
	ContextId string `json:"ContextId,omitempty"`
	ExerciseMethod []string `json:"ExerciseMethod,omitempty"`
	PriceReferenceId string `json:"PriceReferenceId,omitempty"`
	QuoteId string `json:"QuoteId,omitempty"`
	TradeIdeaId int32 `json:"TradeIdeaId,omitempty"`
	UserPrice float64 `json:"UserPrice,omitempty"`
}
