/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body32 struct {
	ValidFrom string `json:"ValidFrom,omitempty"`
	ValidUntil string `json:"ValidUntil,omitempty"`
}
