/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body17 struct {
	CaseTitle    string `json:"CaseTitle,omitempty"`
	ClientKey    string `json:"ClientKey,omitempty"`
	Description  string `json:"Description,omitempty"`
	NotifyClient bool   `json:"NotifyClient,omitempty"`
	ShowInPortal bool   `json:"ShowInPortal,omitempty"`
}
