/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body71 struct {
	AccountKey string `json:"AccountKey,omitempty"`
	DecisionMakerUserID int32 `json:"DecisionMakerUserID,omitempty"`
	MultiLegAmount float64 `json:"MultiLegAmount,omitempty"`
	MultiLegOrderId string `json:"MultiLegOrderId,omitempty"`
	OrderPrice float64 `json:"OrderPrice,omitempty"`
	TraderId string `json:"TraderId,omitempty"`
}
