/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body68 struct {
	AccountKey                   string        `json:"AccountKey,omitempty"`
	AlgoOrderData                *interface{}  `json:"AlgoOrderData,omitempty"`
	AllocationKeyId              string        `json:"AllocationKeyId,omitempty"`
	Amount                       float64       `json:"Amount,omitempty"`
	AmountType                   []string      `json:"AmountType,omitempty"`
	AppHint                      int32         `json:"AppHint,omitempty"`
	AssetType                    []string      `json:"AssetType,omitempty"`
	BuySell                      []string      `json:"BuySell,omitempty"`
	CancelOrders                 bool          `json:"CancelOrders,omitempty"`
	ClearForceOpen               bool          `json:"ClearForceOpen,omitempty"`
	DecisionMakerUserID          int32         `json:"DecisionMakerUserID,omitempty"`
	ExternalReference            string        `json:"ExternalReference,omitempty"`
	ForwardDate                  string        `json:"ForwardDate,omitempty"`
	IsForceOpen                  bool          `json:"IsForceOpen,omitempty"`
	ManualOrder                  bool          `json:"ManualOrder,omitempty"`
	OrderDuration                *interface{}  `json:"OrderDuration,omitempty"`
	OrderId                      string        `json:"OrderId,omitempty"`
	OrderPrice                   float64       `json:"OrderPrice,omitempty"`
	OrderType                    []string      `json:"OrderType,omitempty"`
	Orders                       []interface{} `json:"Orders,omitempty"`
	PositionId                   string        `json:"PositionId,omitempty"`
	StopLimitPrice               float64       `json:"StopLimitPrice,omitempty"`
	SwitchInstrumentUic          int32         `json:"SwitchInstrumentUic,omitempty"`
	ToOpenClose                  []string      `json:"ToOpenClose,omitempty"`
	TraderId                     string        `json:"TraderId,omitempty"`
	TrailingStopDistanceToMarket float64       `json:"TrailingStopDistanceToMarket,omitempty"`
	TrailingStopStep             float64       `json:"TrailingStopStep,omitempty"`
	TraspasoIn                   *interface{}  `json:"TraspasoIn,omitempty"`
	Uic                          int32         `json:"Uic,omitempty"`
}
