/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Openapicmv1signupsBankInformation struct {
	BeneficiaryBankName     string `json:"BeneficiaryBankName,omitempty"`
	ReceivingCountryIsoCode string `json:"ReceivingCountryIsoCode,omitempty"`
}
