/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Openapicmv1signupsAccountInformation struct {
	AdditionalChoiceOfAccounts []string `json:"AdditionalChoiceOfAccounts,omitempty"`
	ClientCategoryId string `json:"ClientCategoryId,omitempty"`
	CurrencyCode string `json:"CurrencyCode,omitempty"`
	IntendedCommissionGroupId string `json:"IntendedCommissionGroupId,omitempty"`
	IntendedTemplateId string `json:"IntendedTemplateId,omitempty"`
	OtherInstructions string `json:"OtherInstructions,omitempty"`
}
