/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Openapicmv1signupsFinlandData struct {
	EuroclearJudicialForm string `json:"EuroclearJudicialForm,omitempty"`
	EuroclearSectorCode string `json:"EuroclearSectorCode,omitempty"`
}
