/*
 * Swagger Saxo Bank openapi
 *
 * Saxo Bank openapi for trading
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saxo_openapi

type Body56 struct {
	AllocationKeyName string `json:"AllocationKeyName,omitempty"`
	AllocationUnitType []string `json:"AllocationUnitType,omitempty"`
	MarginHandling []string `json:"MarginHandling,omitempty"`
	OneTime bool `json:"OneTime,omitempty"`
	OwnerAccountKey string `json:"OwnerAccountKey,omitempty"`
	ParticipatingAccountsInfo []interface{} `json:"ParticipatingAccountsInfo,omitempty"`
}
